apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valult-app
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/hashicorp/vault-helm.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: injector.replicas
          value: '3'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
