apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd   # namespace where the argocd server is running
spec:
  destination:
    namespace: qa     # namespace where the application should deploy
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/hashicorp/vault-helm.git'
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #     - values.yaml
    #   parameters:
    #     - name: injector.replicas
    #       value: '2'
  sources: []
  project: default
  syncPolicy:
  automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
