apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-application
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kubernetes-external-secrets
    repoURL: 'https://github.com/external-secrets/kubernetes-external-secrets.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: '3'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
