apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: replicaCount
          value: '3'
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
