apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/hashicorp/vault-helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: injector.replicas
          value: '2'
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
